package com.dal.noac.model;

// Generated Oct 26, 2014 5:44:33 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Entity;
import org.hibernate.annotations.Table;

/**
 * Drug generated by hbm2java
 */

public class Drug implements java.io.Serializable {

	private int id;
	private String name;
	private Set<Noacform> noacforms = new HashSet<Noacform>(0);

	public Drug() {
	}

	public Drug(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public Drug(int id, String name, Set<Noacform> noacforms) {
		this.id = id;
		this.name = name;
		this.noacforms = noacforms;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Noacform> getNoacforms() {
		return this.noacforms;
	}

	public void setNoacforms(Set<Noacform> noacforms) {
		this.noacforms = noacforms;
	}

}
