package com.dal.noac.model;

// Generated Oct 26, 2014 5:44:33 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Noacform generated by hbm2java
 */
public class Noacform implements java.io.Serializable {

	private int id;
	private Drug drug;
	private Province province;
	private String title;
	private List<Outcome> outcomes = new ArrayList<Outcome>(0);
	private List<Section> sections = new ArrayList<Section>(0);

	public Noacform() {
	}

	public Noacform(int id) {
		this.id = id;
	}

	public Noacform(int id, Drug drug, Province province, String title,
			List<Outcome> outcomes, List<Section> sections) {
		this.id = id;
		this.drug = drug;
		this.province = province;
		this.title = title;
		this.outcomes = outcomes;
		this.sections = sections;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Drug getDrug() {
		return this.drug;
	}

	public void setDrug(Drug drug) {
		this.drug = drug;
	}

	public Province getProvince() {
		return this.province;
	}

	public void setProvince(Province province) {
		this.province = province;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public List<Outcome> getOutcomes() {
		return this.outcomes;
	}

	public void setOutcomes(List<Outcome> outcomes) {
		this.outcomes = outcomes;
	}

	public List<Section> getSections() {
		return this.sections;
	}

	public void setSections(List<Section> sections) {
		this.sections = sections;
	}

}
