package com.dal.noac.model;

// Generated Oct 26, 2014 5:44:33 PM by Hibernate Tools 4.3.1

/**
 * Noacfieldselectoptions generated by hbm2java
 */
public class Noacfieldselectoptions implements java.io.Serializable {

	private int id;
	private Noacfield noacfield;
	private String value;
	private String label;

	public Noacfieldselectoptions() {
	}

	public Noacfieldselectoptions(int id, Noacfield noacfield, String value,
			String label) {
		this.id = id;
		this.noacfield = noacfield;
		this.value = value;
		this.label = label;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Noacfield getNoacfield() {
		return this.noacfield;
	}

	public void setNoacfield(Noacfield noacfield) {
		this.noacfield = noacfield;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

}
